### ISSUE TITLE
Fix Base Parsing

### ISSUE THREAD

**Issue by nickumia** [nickumia/web-search-dictionary#5]
Randomly tried this word and it failed.
```
$ python example.py world
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    entry = websearchdict.lookup(sys.argv[1])
  File "/home/kamutiv/web-search-dictionary/websearchdict/__init__.py", line 13, in lookup
    parsed = LXML_preprocessHTML(web_response)
  File "/home/kamutiv/web-search-dictionary/websearchdict/web/parser.py", line 52, in LXML_preprocessHTML
    hdoc = etree.fromstring(content)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: hr line 1 and div, line 1, column 16004
```

**Comment by nickumia** [comment]
The problem was that `<hr>` tags were not being truncated.  They are safe to ignore because they are not data-carrying tags.
